### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aleveille**
Update README.md version of the action from v3 (deprecated NodeJS 16) to v4 (NodeJS 20)

### CODE REVIEW

**Comment by aleveille** [comment]
@OliverMKing @jaiveerk
I think this would help a lot of people avoid using the deprecated Node16 version of this action

**Comment by ay0o** [comment]
Just "faced" this issue. I was reviewing a third-party workflow and noticed they were using `azure/setup-kubectl@v4` but the README says `v3`, so I had to actually check the releases to be sure that `v4` exists.

So, indeed, let's update the README to show the latest version.

**Comment by aleveille** [comment]
@erinborders @bfoley13 @davidgamero Trying to get an approval on this simple README change. Thanks for any help :)

**Comment by gustavo-mungarro** [comment]
+1 - simple, but useful.

**Review by davidgamero — APPROVED** [review]
lgtm thank you for updating this

**Review by jaiveerk — APPROVED** [review]

**Pull request merged**
